[package]
name = "read_csv"
version = "0.1.0"
authors = ["Yuttakhan Baingen <yuttakhanbaingen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rustc-serialize = "0.3"
